-- MANAGER

CREATE TABLE MANAGER (
MANAGER_ID INT PRIMARY KEY,
MANAGER_NAME VARCHAR(40) NOT NULL,
MANAGER_CONTACT INT NOT NULL,
MANAGER_ADDRESS VARCHAR(100) NOT NULL
);

-- TENANTS

CREATE TABLE TENANTS (
TENANT_ID INT PRIMARY KEY,
TENANT_NAME VARCHAR(30) NOT NULL,
TENANT_ADDRESS VARCHAR(100) NOT NULL,
TENANT_CONTACT INT NOT NULL
);

-- PROPERTY

CREATE TABLE PROPERTY (
PROPERTY_ID INT PRIMARY KEY,
MANAGER_ID INT NOT NULL,
UNIT_COUNT INT NOT NULL,
PROPERTY_OWNER VARCHAR(40) NOT NULL,
PROPERTY_ADDRESS VARCHAR(100) NOT NULL,
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);

-- OWNER

CREATE TABLE OWNER (
OWNER_ID INT PRIMARY KEY,
PROPERTY_ID INT NOT NULL,
MANAGER_ID INT NOT NULL,
OWNER_NAME VARCHAR(40) NOT NULL,
OWNER_CONTACT INT NOT NULL,
OWNER_ADDRESS VARCHAR(100) NOT NULL,
FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);



-- UNIT

CREATE TABLE UNIT (
UNIT_ID INT PRIMARY KEY,
MANAGER_ID INT NOT NULL,
OWNER_ID INT NOT NULL,
TENANT_ID INT ,
UNIT_RENT INT NOT NULL,
UNIT_OWNER VARCHAR(50) NOT NULL,
UNIT_ADDRESS VARCHAR(100) NOT NULL,
FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID),
FOREIGN KEY (OWNER_ID) REFERENCES OWNER(OWNER_ID),
FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);


-- MAINTENANCE

CREATE TABLE MAINTENANCE (
MAIN_ID INT PRIMARY KEY,
UNIT_ID INT NOT NULL,
MAIN_AMOUNT INT NOT NULL,
TENANT_CONTACT INT NOT NULL,
MAIN_START_DATE DATE,
MAIN_END_DATE DATE,
MAIN_TYPE VARCHAR(30),
FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID)
);

--LEASE

CREATE TABLE LEASE (
LEASE_ID INT PRIMARY KEY,
UNIT_ID INT NOT NULL,
TENANT_ID INT NOT NULL,
LEASE_AMOUNT INT NOT NULL,
OWNER_NAME VARCHAR(40) NOT NULL,
MANAGER_CONTACT INT NOT NULL,
LEASE_START_DATE DATE, 
LEASE_END_DATE DATE,
FOREIGN KEY (UNIT_ID) REFERENCES UNIT(UNIT_ID),
FOREIGN KEY (TENANT_ID) REFERENCES TENANTS(TENANT_ID)
);
